### PR TITLE
Binary editted client for boomerang step edge & allowing bstep while jumping

### PR DESCRIPTION
**Pull request by hellionak**
Binary edited the checks for edges on boomerang step and allowed using boomerang step while jumping. Special thanks to Shahar#2563 from discord for revealing the relevant memory addresses for change.

### CODE REVIEW

**Review by dgerkol — COMMENTED** [review]
When compiling the new client, which IP addresses & settings did you use?
Everything must be the same as the prod server, or else players won't be able to connect.

Also, we have legacy client, does it also have the bug?
Did we fix it same as here?

**Comment by hellionak** [comment]
> 
I've used the production client. For testing I logged in to the production server and seen that the shadower can attack with boomerang step as expected.

**Review by dgerkol — APPROVED** [review]
Tested client, seems to be working fine.

**Comment by dgerkol** [comment]
Merging with singly review after testing on prod

**Pull request merged**
